### PR TITLE
Changes to public repo regarding small errors and missing import stat…

### PR DESCRIPTION
**Pull request by jonathansong1**
…ements in shapexplain, evalmodels, and utils.

### CODE REVIEW

**Comment by sslou** [comment]
what's in song_additionals? also, you should keep NOTHBLEED_d0. it looks like the other change is re: CPT instead of CPT_name, is that right?

**Comment by jonathansong1** [comment]
from song_additionals import * should import the following function. I grabbed this function from the private repo (NSQIP_bin_classify_SL.py) since it was missing in the public repo.

`def perform_imputation(data, imputer=None):
    if imputer == None:
        imp = SimpleImputer(missing_values=np.nan, strategy='median')
        imp.fit(data)
    else:
        imp = imputer
    data = imp.transform(data)
    return pd.DataFrame(data), imp`

Ok, understood on the NOTHBLEED_d0 comment.

Yes, CPT_name should be changed to CPT

**Comment by sslou** [comment]
Could you throw that function into `utils.py` and undo the NOTHBLEED_d3 -> NOTHBLEED_d0? Then I think we can merge.

**Comment by jonathansong1** [comment]
Final changes made.

**Comment by sslou** [comment]
Thanks, look good! I merged it in.

**Pull request merged**
